### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by BahabaBeast** [VRPirates/rookie#101]
---------------------------
Unable to connect to Remote Server
---------------------------
Unable to connect to Remote Server. Rookie is unable to connect to our Servers.

First time launching Rookie? Please relaunch and try again.

Things you can try:
1) Move the Rookie directory (Folder containing AndroidSideloader.exe) into C:\RSL
2) Try changing your systems DNS to either Cloudflare/Google/OpenDNS
3) Try using a systemwide VPN like ProtonVPN (which is free)
4) Sponsor a private server (https://vrpirates.wiki/en/Howto/sponsored-mirrors)

---------------------------
OK   
---------------------------

this happens to me and i dont understand it could anybody help

**Comment by Fenopy** [comment]
This is not an application issue.
Please use our Telegram or Discord channels for Support as mirrors and instructions change.
https://vrpirates.wiki/en/general_information/live-chats

As of today, the below steps are the standard connection troubleshooting steps.

Is Rookie unable to connect? Check out the below troubleshooting steps-

Make sure you are using the latest version of Rookie (https://vrpirates.wiki/en/general_information/vrp-downloads)!
Do you have a file called vrp-public.json in your Rookie folder? Just create a file named vrp-public.json, a blank file works just fine! Make sure the extension is .json, not a .txt file.
Verify you can get to raw.githubusercontent.com (https://raw.githubusercontent.com/) (Should auto-forward to the Github home page).
Verify you can get to downloads.rclone.org (https://downloads.rclone.org/).
Verify you can reach our Wiki, vrpirates.wiki (https://vrpirates.wiki/)
Can you get to theapp.vrrookie.xyz (https://theapp.vrrookie.xyz/)? (You should get "Sorry, you have been blocked"; That means it is working 😉)
Try changing your DNS to a Public, non-censoring DNS service, such as Cloudflare (https://developers.cloudflare.com/1.1.1.1/setup/windows/), Google (https://developers.google.com/speed/public-dns/docs/using), or OpenDNS (https://support.opendns.com/hc/en-us/articles/228007207-Windows-10-Configuration)
If you've made it this far, your ISP is likely blocking you. You will need to try using a VPN (https://gprivate.com/5yxo8) to connect.
Did a VPN fix your Problem? Your Router or Anti-Virus Firewall may be blocking Rookie Servers. Check out this post (https://rentry.co/ASUSRouterBlock) for more information.
