### ISSUE TITLE
rookie vr clone error

### ISSUE THREAD

**Issue by Andy241181** [VRPirates/rookie#103]
hi,  today i tried to use rookie but i keep getting r/clone error message. iv just seen that i need to add "vrp-public.json file to the rookie destination. can someone guide me in to where i would be able to download this file to add to the rookie destination please. i love this program

**Comment by Fenopy** [comment]
This is not an application issue. Please usetb the VRP support channels for assistance connecting to VRP mirrors
https://vrpirates.wiki/en/general_information/live-chats
