### ISSUE TITLE
Sideloader 2.92.2 download resume fails

### ISSUE THREAD

**Issue by victorg001** [VRPirates/rookie#109]
Just updated sideloader 2 latest version.
In release notes i saw download resume option. 
It's confusing that resume stops working 4 me, although it works in previous versions: even if I close app, then start it again and choose app\game to download, it resumes downloading. 
Now it's completely resets and starts from beginning...

**Comment by Fenopy** [comment]
Resuming is only per part. All parts are 500mb or less. So at least one 500mb part has to finish for resuming to work. There is no resuming on a partial part.

If this doesn't answer your issue, please provide actual details on what is occurring, debug logs, etc...
