### ISSUE TITLE
cant open rookie

### ISSUE THREAD

**Issue by nimka-uiu** [VRPirates/rookie#114]
whenever i try to open rookie it says the following: ---------------------------

---------------------------
You are unable to access the raw.githubusercontent.com page with the Exception: An exception occurred during a WebClient request.
Some files may be missing (ADB, Offline Script, Launcher)
---------------------------
OK   
---------------------------
---------------------------

---------------------------
These required files were unable to be downloaded
Rookie will now close, please use Offline Mode for manual sideloading if needed
---------------------------
OK   
---------------------------
and I dont know what i should do?

**Comment by JLubranoL** [comment]
Hi @nimka-uiu!

Try creating the folder and sub-folders as following as specified on the [VRP page](https://wiki.vrpirates.club/en/Howto/Rookie-Sideloader#:~:text=%C2%B6-,Download%20current%20version,-The%20current%20version): `C:/RSL/Rookie`
Remember to exclude the _**RSL**_ folder from your antivirus.
Then, you can extract the **_Sideloader.exe_** inside your **_Rookie_** folder. 
A more detailed explanation step by step is in the link I provided above

Hope this helps!

**Comment by frxctura** [comment]
The issue you're facing with accessing `raw.githubusercontent.com` is not from our end. It seems to be related to your network or firewall settings (possibly within your Router/Antivirus). Please check your internet connection or try using a VPN.

Closing this issue.
