### ISSUE TITLE
Can't instal Rookie

### ISSUE THREAD

**Issue by augustojv12** [VRPirates/rookie#126]

**Comment by augustojv12** [comment]
Hi guys,

I've just tried to install Rookie on my PC, but it doesn't install when I first open the AndroidSideloader.exe

It opens the "Loading assets" pop up, but Windows says "AndroidSideloader is not responding"

Here's the error

You are unable to access the rclone page with the Exception: Exceção durante uma solicitação do WebClient.
Some files may be missing (RCLONE)

*There's a part in portughese, because I'm brazilian, but hope you understand*

Here's the crash log:

Date/Time of crash: quarta-feira, agosto 21 @ 09:06 (UTC)
Message: O sistema não pode encontrar o arquivo especificado
Inner Message: None
Data: System.Collections.ListDictionaryInternal
Source: System
TargetSite: Boolean StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)
Stack Trace: 
   em System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   em System.Diagnostics.Process.Start()
   em AndroidSideloader.RCLONE.runRcloneCommand_DownloadConfig(String command)
   em AndroidSideloader.MainForm.initMirrors(Boolean random)
   em AndroidSideloader.MainForm.<Form1_Shown>b__33_1()
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()


Debuglog:

------

Really hope you can help me. Thanks in advance.

**Comment by Fenopy** [comment]
Is Rookie unable to connect? Check out the below troubleshooting steps-

1. Make sure you are using the [latest version of Rookie](https://vrpirates.wiki/en/general_information/vrp-downloads)!
2. Do you have a file called *vrp-public.json* in your Rookie folder? Just create a file named vrp-public.json, a blank file works just fine! _Make sure the extension is .json, not a .txt file_.
3. Verify you can get to [raw.githubusercontent.com](https://raw.githubusercontent.com/) (_Should auto-forward to the Github home page_).
4. Verify you can get to [downloads.rclone.org](https://downloads.rclone.org/).
5. Verify you can reach our Wiki, [vrpirates.wiki](https://vrpirates.wiki/)
6. Can you get to [theapp.vrrookie.xyz](https://theapp.vrrookie.xyz/)? (_You should get "Sorry, you have been blocked"; That means it is working_ 😉)
7. Try changing your DNS to a Public, non-censoring DNS service, such as [Cloudflare](https://developers.cloudflare.com/1.1.1.1/setup/windows/), [Google](https://developers.google.com/speed/public-dns/docs/using), or [OpenDNS](https://support.opendns.com/hc/en-us/articles/228007207-Windows-10-Configuration)
8. If you've made it this far, your ISP is likely blocking you. You will need to try [using a VPN](https://gprivate.com/5yxo8) to connect. 
9. Did a VPN fix your Problem? Your Router or Anti-Virus Firewall may be blocking Rookie Servers. Check out [this post](https://rentry.co/ASUSRouterBlock) for more information.
