### ISSUE TITLE
Crash deleting folder

### ISSUE THREAD

**Issue by wraithguardomega** [VRPirates/rookie#132]
I had the app running just on the desktop, and typically when it runs it creates a bunch of other files, but when it crashed it deleted a bunch of stuff off my desktop. This included some folders/files that the app hadn't created itself. And it didn't even deleted them to the recycle bin, they're just gone completely. 
I had a folder on my desktop called desktop where i dumped a bunch of mess i needed to sort, some 3d print files, things i cant even remember what was there now, and now it's all just gone.

would be great if it didn't do this. and any idea how i can undelete my stuff?

**Comment by Fenopy** [comment]
Rookie can't and didn't do this.
Check your recycle bin.
Don't run applications from your desktop. Run them from their own folder, ideally in C:/RSL/Rookie

**Comment by wraithguardomega** [comment]
so rookie has no ability to delete any files/folders? then how did i literally just watch it delete and create files when "updating metadata" when i started it...

**Comment by Fenopy** [comment]
Of course it deletes files and folders, it does it all the time.

But they aren't necessarily targeted. Rookie can clean up "its directory", so if you screwed up, and ran a straight EXE from your desktop, then who knows what it will clean up trying to "fix itself".

IE: Why would you ever run an EXE straight from the desktop. We provide it in a folder for a reason, and suggest extracting it into a folder for a reason.

**Comment by wraithguardomega** [comment]
so you admit now that "i screwed myself". meaning it can do exactly what i said it did....

why would i run it from the desktop? because the desktop is a folder, just like every other folder. I never read anything saying to run it in its own folder, definitely nothing warning to do that because it might just randomly delete everything in the folder its in. 

"We provide it in a folder for a reason, and suggest extracting it into a folder for a reason." all of your releases contain just the exe file. its not even zipped so that it would extract with the exe in a folder. so in what way is it "provided in a folder"? 
I also just double checked, i cant find any mention anywhere saying to put it in its own folder. 
It only comes in a folder if someone downloads the source code.


"then who knows what it will clean up trying to "fix itself"."

well i would have thought you would know what it would do, you coded the thing, no? you coded it to just delete everything if it crashes?.. theres a reason software like this gets flagged as being a virus... just deleting things, and the creator not even knowing what it will delete... thats pretty "virus" worthy activity.
