### ISSUE TITLE
Unable to connect to Remote Server Error!

### ISSUE THREAD

**Issue by CODEKINGOMER** [VRPirates/rookie#138]
Hi, I have been using rookie for a long time. I recently logged into Rookie and got an error. At first I thought it was related to my PC and I tried it on another PC. But the result did not change.
(When I Downloaded Something, It Says File Not Found And Cancels The Process). Then I didn't use Rookie for like a month. And when I downloaded the current version today, it gave the following error:

Unable to connect to Remote Server
Unable to connect to Remote Server. Rookie is unable to connect to our Servers.
First time launching Rookie? Please relaunch and try again.
Please visit our Telegram (https://t.me/VRPirates) or Discord (https://discord.gg/DcfEpwVa4a) for Troubleshooting steps!

I looked at a lot of Reddit and VRPriatees articles, but my problem was not solved. I hope you can solve my problem.

**Comment by caiomcg** [comment]
Have the same issue. Service was working normally yesterday, September 20th.

**Comment by CODEKINGOMER** [comment]
Is What Causes This Related to the Servers?

**Comment by CODEKINGOMER** [comment]
Is there anything I can do?
(NOTE: I created a text document named vrp.public.json and threw it into the folder, nothing changed)

**Comment by caiomcg** [comment]
> Is there anything I can do? (NOTE: I created a text document named vrp.public.json and threw it into the folder, nothing changed)

Maybe a dev or a more experienced community member can help you. My installation 2.32.0 no longer has the issue. Think it was programmed downtime.

**Comment by CODEKINGOMER** [comment]
Are You Not Having This Issue In The Latest Version?

**Comment by CODEKINGOMER** [comment]
I Use 2.30.0

**Comment by CODEKINGOMER** [comment]
WHAT?! I Reinstalled Version 2.30.0 and It Works. I guess it was planned. Thanks for Helping Dude!
