### ISSUE TITLE
7zip error

### ISSUE THREAD

**Issue by C0lyn** [VRPirates/rookie#139]
When downloading any game it say 7zip can extract this file and its really annoying me so help me

Please
:)

**Comment by Alex130988** [comment]
Hi, I had the same problem. When I moved the installation file to a separate folder on my desktop. I then started it as admin and everything worked.

Hope this helps you.

Kind regards
Alex130988

**Comment by Fenopy** [comment]
Please refer to the readme.
https://github.com/VRPirates/rookie#disclaimer
https://github.com/VRPirates/rookie#support
