### ISSUE TITLE
gets error when trying to install a game

### ISSUE THREAD

**Issue by Archviz360** [VRPirates/rookie#142]
Error: adb: failed to stat C:\Users\USER\Desktop\oculus-go--driver-2.0\Toy Trains v1003013+01.003.013 -VRP\com.smtrandom.toytrain.apk: No such file or directory

**Comment by frxctura** [comment]
This doesn’t look like a problem with the code itself but more likely an issue with your file path or antivirus.
Please refer to the readme.
https://github.com/VRPirates/rookie#support

**Comment by Archviz360** [comment]
fixed the issue :)
