### ISSUE TITLE
[Enhancement Request] Log box rather than dialog for each notification

### ISSUE THREAD

**Issue by Sombody101** [VRPirates/rookie#144]
Can a logging box be created for things such as ADB output and tasks? The option `Enable Message Boxes on task completed` does help, but there are still a ton of dialogs that only say `Output: success`.

Obviously, dialog boxes are needed when user input is needed, but it would be cleaner if all other output didn't require user input as well.

**Comment by frxctura** [comment]
Committed fix in [beta/RSL-2.31](https://github.com/VRPirates/rookie/commit/f85d43d701495fd15f79e855f904c7c0599513a4)

**Comment by Sombody101** [comment]
> Process Outputs still appear

The main item I'm trying to address in this request is the need to click "Okay" or close a dialog box for information that should not require an action to be taken. An example is trying to uninstall several games or apps from a headset. You need to select the specific game, click uninstall, go through two more dialog boxes (one for confirming you want to delete the game, and another asking if you'd like to create a backup), and then you get the "Output: success" output which requires another click to close the dialog. Then you can move on to the other games or apps (assuming you have the `Enable Message Boxes on task completed` unchecked, or you'd get another dialog giving verbose information about the action). It becomes tedious.

I only used a log box that the user sees at all times as an example of where this could be displayed, all without the need to navigate to a submenu and open a file. An example being [Phunk](https://github.com/shibadevs/phunk) where the user is given a log box to show what Phunk is doing, and any action that requires direct user input is done via a dialog.
