### ISSUE TITLE
[Feature Request] Indicate Free games or show game price

### ISSUE THREAD

**Issue by xDerApfelx** [VRPirates/rookie#145]
I dont know how realistic this feature is. I was just scrolling through rookie and found some great looking games i wanted to try. One of them was a free game. If there is a free game I dont need to use rookie for that. I just could "buy" the free game on the quest and download it from the store. It would probably be a bit faster due too the obb file transfer process of rookie, also the updating of the game would also be easier.
So maybe some kind of indicator that the game is free

**Comment by Fenopy** [comment]
We don't share free games.

The free games have In-App-Purchases unlocked.

**Comment by xDerApfelx** [comment]
Ok i didnt know that. Thank you
