### ISSUE TITLE
What do I do if I downloaded Batman Arkham Shadow, then deleted it after I thought it was broken?

### ISSUE THREAD

**Issue by Masterhat165** [VRPirates/rookie#152]
I did that, and when I try to put the game in the quest 2 it only puts the obb folder, and it doesn't show in the unknown sources tab.

**Comment by frxctura** [comment]
This is not an application issue.

Please refer to the readme.
https://github.com/VRPirates/rookie#disclaimer
https://github.com/VRPirates/rookie#support
