### ISSUE TITLE
[Feature Request] Allow for offline use to sideload APKs from PC to headset.  

### ISSUE THREAD

**Issue by DaveC1964** [VRPirates/rookie#153]
Rookie complains server not found if offline then "OK" exits app.  I would want to use offline if internet/server not available on a particular PC to sideload APK to headset and copy obb to headset.  I have backup APKs on HDD so they can be swapped in and out of headset storage when full without having to wait for re-download.  It should be simple enough to just not exit app after server not found message comes up and "OK" is selected.

**Comment by Fenopy** [comment]
That is why we include a "Rookie Offline" file....
Launch AndroidSideloader with the argument --offline
