### ISSUE TITLE
virus Warning 

### ISSUE THREAD

**Issue by Fenrir676** [VRPirates/rookie#157]
Got a virus Warning after try to install. Win11

**Comment by frxctura** [comment]
Please refer to the readme, specifically:

https://github.com/VRPirates/rookie/blob/master/README.md#L8-L13

**Comment by Subcode** [comment]
for the record, it is not being detected as malware, it is detected as a trojan crypto stealer.

**Comment by frxctura** [comment]
That is by definition malware...you're at the source code, feel free to compile an exe for yourself, we have the steps in the readme aswell.

**Comment by frxctura** [comment]
That is by definition malware...you're at the source code, feel free to compile an exe for yourself, we have the steps in the readme aswell.

**Comment by frxctura** [comment]
Also, for the record, please look at the previous issue posts, this is a re-occuring issue, every new release we post gets flagged more than the older one, it happens every release, and you can find results about it for every release, be it Reddit, Telegram, Discord, or here on GitHub.
