### ISSUE TITLE
Can't sort by popularity anymore

### ISSUE THREAD

**Issue by Nevarnost** [VRPirates/rookie#160]
Since the last update the "Popularity" column isn't sortable anymore

Version: 2.31.1 

![image](https://github.com/user-attachments/assets/fa04d2a0-0e7e-4e63-b65d-0f675d8b53d6)

**Comment by Nevarnost** [comment]
For the record, i preferred the total download counter honestly, this popularity index isn't very explainatory to me

**Comment by MykolaDekusar** [comment]
Same issue

**Comment by Fenopy** [comment]
Commit was missed in last update. Update has been deployed.
2b4ec9af38dda63ca82f5519ee795028d0074f8c
