### ISSUE TITLE
[Feature Request] Add i18n support?

### ISSUE THREAD

**Issue by cxsunflower** [VRPirates/rookie#162]
Hi there, thanks to the VRP team for developing a very user-friendly program. Have you considered adding i18n support?

**Comment by frxctura** [comment]
If by i18n support you mean general localization, it's been thought about, however would also be a small feat to accomplish.
If you actually mean i18n...
Doesn't that just run on React/JavaScript Applications?

**Comment by cxsunflower** [comment]
> If by i18n support you mean general localization, it's been thought about, however would also be a small feat to accomplish. If you actually mean i18n... Doesn't that just run on React/JavaScript Applications?

I mean general localization❤️
