### ISSUE TITLE
RSL 2.31.2 infected with HackTool:Win32/Tnega

### ISSUE THREAD

**Issue by davidp57** [VRPirates/rookie#165]
Hi there,
Seems that Windows Defender found the signature of this trojan in the main executable of this release...

**Comment by McModdyWorld** [comment]
prolly false positive yk

**Comment by frxctura** [comment]
Please refer to the readme, specifically:

https://github.com/VRPirates/rookie/blob/master/README.md#L8-L13


For even further clarification, see this post:
https://www.reddit.com/r/QuestPiracy/s/XdSy27fkGk
