### ISSUE TITLE
Sideload no more?

### ISSUE THREAD

**Issue by CursedOddity** [VRPirates/rookie#166]
After updating to V72, all of my RSL installs have been removed. The entire section for unofficial or whatever it was called is now gone. 

Is this the end of RSL?

**Comment by frxctura** [comment]
This is not an application issue.

Please refer to the readme.
https://github.com/VRPirates/rookie#support

**Comment by CursedOddity** [comment]
Yes I see the unknown sources section again. I wonder why it disappeared for a while?? Strange. Sorry to waste your time.
