### ISSUE TITLE
Debiant / Linux When?

### ISSUE THREAD

**Issue by Satanaelcode** [VRPirates/rookie#22]
To maḱe Linux Support sould not be a big thing it even could just be a barebones CLI just give us an option to get games man xd

**Comment by Fenopy** [comment]
Not an application issue. This is open source for a reason, feel free to contribute.

**Comment by MaximalCats** [comment]
@Satanaelcode If you're still looking for a solution for this, i brew up a [small python script](https://git.clatter.cc/hexlocation/vrp-easy) a few months ago that **downloads** (doesn't install them) games from the mirror. You'll have to install the games yourself via ADB.

**Comment by victorwads** [comment]
Now you can:
https://github.com/victorwads/QRookieNode/releases

Not only on Linux, but on Mac and even inside Quest or any Android Device
