### ISSUE TITLE
OBB Unable to copy

### ISSUE THREAD

**Issue by Cabbittron** [VRPirates/rookie#26]
I don't no where else i can post about this but i was hoping it would be okay to ask. 

So I got the Quest 3 on launch day today. Tried Rooker 2.23 however when trying to install games via it, it shows an error regarding being able to copy OBB information. 

"OBB Size Mismatch!
Warning ! It seems like the OBB wasn't pushed correctly, this means that the game may not launch correctly. Do you want to retry the push ?"

**Comment by miguel-mpm** [comment]
same here. There's a reddit thread with more reports confirming the issue: https://www.reddit.com/r/QuestPiracy/comments/174pnh9/just_got_my_quest_3_but_have_run_into_an_issue/

**Comment by Chax1** [comment]
We're fully aware and working on this already. ty.

**Comment by Cabbittron** [comment]
> We're fully aware and working on this already. ty.

You folks are amazing! Thank you for the hard work 😊

**Comment by Chax1** [comment]
We have put out a beta release for now on our wiki that seems to have resolved this issue, thank you for your patience.
