### ISSUE TITLE
cannot connect to remote server

### ISSUE THREAD

**Issue by axlylol** [VRPirates/rookie#32]
i saw the issue before me and i need to ask, how can i fix this? ive tried everything but also i cannot find a discord server for rookie, anything i can do?
![image](https://github.com/VRPirates/rookie/assets/62974139/ff65578d-a077-4040-bc9c-c8147f003c58)

**Comment by axlylol** [comment]
i also do not have a phone so i cant really, yk, download tg, so if i could get a discord link that'd be cool

**Comment by Chax1** [comment]
This is not an application issue, but an internet issue. servers are up. use support channels (tg/discord), not git for support.
You can find a link to our Discord on our wiki page 🙂

**Comment by PJFonseca** [comment]
@axlylol just download this https://wiki.vrpirates.club/downloads/vrp-public.json and put it on the root folder where the exe file is. It worked for me.
