### ISSUE TITLE
yet again, no connection to servers

### ISSUE THREAD

**Issue by axlylol** [VRPirates/rookie#33]
this is definitely an issue on your end, reason being is because
1. you've told 3 people by now including me to "check the discord"
2. the wiki literally is down and has not been up for the last 3 days meaning we cant get to the discord for support
3. i've tried on 2 different networks, and 2 different computers with 2 different networks neither working, i have tried ethernet and still nothing
this is definitely an issue on your end and i believe you should attempt to get this resolved because as of now, from what i can see not a lot of people can use rookie

**Comment by Fenopy** [comment]
Everything is working. We cannot fix your ISP censoring your internet.

**Comment by PJFonseca** [comment]
> this is definitely an issue on your end, reason being is because
> 
>     1. you've told 3 people by now including me to "check the discord"
> 
>     2. the wiki literally is down and has not been up for the last 3 days meaning we cant get to the discord for support
> 
>     3. i've tried on 2 different networks, and 2 different computers with 2 different networks neither working, i have tried ethernet and still nothing
>        this is definitely an issue on your end and i believe you should attempt to get this resolved because as of now, from what i can see not a lot of people can use rookie

@axlylol just download this https://wiki.vrpirates.club/downloads/vrp-public.json and put it on the root folder where the exe file is. It worked for me.
