### ISSUE TITLE
Drag and Drop of Predownloaded Games fails on Quest 3

### ISSUE THREAD

**Issue by mmeissner** [VRPirates/rookie#37]
The fix of calling "RunAdbCommandToString($"shell mkdir /sdcard/Android/obb/{folder}") is not executed if the predownloaded game gets installed by drag and drop of its folder onto the application.

Dirty Fix in ADB Class:

public static ProcessOutput CopyOBB(string path)
        {
            string folder = Path.GetFileName(path);
            if (!folder.Contains("+") && !folder.Contains("_") && folder.Contains("."))
            {
                RunAdbCommandToString($"shell mkdir /sdcard/Android/obb/{folder}");
                return RunAdbCommandToString($"push \"{path}\" \"/sdcard/Android/obb\"");   
            }
            else
                return new ProcessOutput();
        }

**Comment by Chax1** [comment]
As of #50 this should be fixed.
