### ISSUE TITLE
Unable to connect to Remote Server

### ISSUE THREAD

**Issue by hectorchanht** [VRPirates/rookie#38]
still able to download games last night, but not today.
The .exe is put inside C:\RSL
8.8.8.8 and 1.1.1.1 dns is used, proton vpn is used

my guess is that https://skrazzle.glomtom.cyou/meta.7z was failing to provide services

`
03:54:39.507 AM (UTC): [INFO] [MainForm.InitializeLogger] 
------
------
Program Launched at: 08:54PM(UTC)
------
------

03:54:39.762 AM (UTC): [INFO] [<Form1_Load>d__31.MoveNext] Starting AndroidSideloader Application
03:54:39.798 AM (UTC): [INFO] [SideloaderRCLONE.updatePublicConfig] Attempting to Update Public Config
03:54:41.185 AM (UTC): [INFO] [SideloaderRCLONE.updatePublicConfig] Retrieved updated config from: https://wiki.vrpirates.club/downloads/vrp-public.json
03:54:41.186 AM (UTC): [INFO] [SideloaderRCLONE.updatePublicConfig] Public config updated successfully.
03:54:41.290 AM (UTC): [INFO] [Sideloader.downloadFiles] Checking for Local rclone...
03:54:41.290 AM (UTC): [INFO] [Sideloader.downloadFiles] Current RCLONE Version 1.62.2
03:54:41.446 AM (UTC): [INFO] [<Form1_Load>d__31.MoveNext] Attempting to Initalize ADB Server
03:54:41.455 AM (UTC): [INFO] [ADB.RunAdbCommandToString] Running command: kill-server
03:54:41.511 AM (UTC): [INFO] [ADB.RunAdbCommandToString] Running command: start-server
03:54:43.604 AM (UTC): [ERROR] [ADB.RunAdbCommandToString] * daemon not running; starting now at tcp:5037
* daemon started successfully

03:54:43.622 AM (UTC): [INFO] [RCLONE.runRcloneCommand_DownloadConfig] Running Rclone command: listremotes --config vrp.download.config
03:54:43.767 AM (UTC): [INFO] [MainForm.initMirrors] Loaded following mirrors: 
03:54:43.784 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Attempting to Update Download Config
03:54:44.129 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Retrieved updated config from: https://wiki.vrpirates.club/downloads/vrp.download.config
03:54:44.131 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Online Config Hash: d41d8cd98f00b204e9800998ecf8427e; Local Config Hash: d41d8cd98f00b204e9800998ecf8427e
03:54:44.131 AM (UTC): [INFO] [SideloaderRCLONE.updateDownloadConfig] Updated Config Hash matches last download. Not updating.
03:54:44.132 AM (UTC): [INFO] [SideloaderRCLONE.updateUploadConfig] Attempting to Update Upload Config
03:54:44.472 AM (UTC): [INFO] [SideloaderRCLONE.updateUploadConfig] Retrieved updated config from: https://wiki.vrpirates.club/downloads/vrp.upload.config
03:54:44.473 AM (UTC): [INFO] [SideloaderRCLONE.updateUploadConfig] Upload config updated successfully.
03:54:44.606 AM (UTC): [INFO] [SideloaderRCLONE.UpdateMetadataFromPublic] Downloading Metadata
03:54:44.608 AM (UTC): [INFO] [RCLONE.runRcloneCommand_PublicConfig] Running Rclone command: sync ":http:/meta.7z" "CurrentDirectory"
03:54:45.749 AM (UTC): [ERROR] [RCLONE.runRcloneCommand_PublicConfig] 2023/11/02 20:54:44 NOTICE: Config file "C:\\Users\\a\\AppData\\Roaming\\rclone\\rclone.conf" not found - using defaults
2023/11/02 20:54:44 ERROR : Attempt 1/3 failed with 1 errors and: failed to stat: Head "https://skrazzle.glomtom.cyou/meta.7z": dial tcp: lookup skrazzle.glomtom.cyou: no such host
2023/11/02 20:54:44 ERROR : Attempt 2/3 failed with 1 errors and: failed to stat: Head "https://skrazzle.glomtom.cyou/meta.7z": dial tcp: lookup skrazzle.glomtom.cyou: no such host
2023/11/02 20:54:45 ERROR : Attempt 3/3 failed with 1 errors and: failed to stat: Head "https://skrazzle.glomtom.cyou/meta.7z": dial tcp: lookup skrazzle.glomtom.cyou: no such host
2023/11/02 20:54:45 Failed to sync: failed to stat: Head "https://skrazzle.glomtom.cyou/meta.7z": dial tcp: lookup skrazzle.glomtom.cyou: no such host

03:54:45.752 AM (UTC): [INFO] [SideloaderRCLONE.ProcessMetadataFromPublic] Extracting Metadata
03:54:45.753 AM (UTC): [INFO] [Zip.DoExtract] Extract: 7z x "C:\RSL\meta.7z" -y -o"C:\RSL\meta"
03:54:45.789 AM (UTC): [INFO] [Zip.DoExtract] 
7-Zip (a) 23.01 (x86) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:

03:54:45.790 AM (UTC): [ERROR] [Zip.DoExtract] 
ERROR: The system cannot find the file specified.
C:\RSL\meta.7z

System ERROR:
The system cannot find the file specified.

03:54:45.790 AM (UTC): [INFO] [SideloaderRCLONE.ProcessMetadataFromPublic] Extracting failed, status code 2
03:54:45.790 AM (UTC): [INFO] [SideloaderRCLONE.ProcessMetadataFromPublic]    at AndroidSideloader.Utilities.Zip.DoExtract(String args)
   at AndroidSideloader.Utilities.Zip.ExtractFile(String sourceArchive, String destination, String password)
   at AndroidSideloader.SideloaderRCLONE.ProcessMetadataFromPublic()

03:54:45.801 AM (UTC): [INFO] [ADB.RunAdbCommandToString] Running command: devices
03:54:45.838 AM (UTC): [INFO] [ADB.RunAdbCommandToString] List of devices attached

03:54:45.902 AM (UTC): [INFO] [<CheckForDevice>d__40.MoveNext] Devices:
03:54:45.919 AM (UTC): [INFO] [ADB.RunAdbCommandToString] Running command: shell df
03:54:45.954 AM (UTC): [ERROR] [ADB.RunAdbCommandToString] adb.exe: no devices/emulators found

03:54:45.959 AM (UTC): [ERROR] [ADB.RunAdbCommandToString] adb.exe: no devices/emulators found

03:54:46.000 AM (UTC): [ERROR] [ADB.RunAdbCommandToString] adb.exe: no devices/emulators found

03:54:46.016 AM (UTC): [INFO] [ADB.RunAdbCommandToString] Running command: shell df
03:54:46.057 AM (UTC): [ERROR] [ADB.RunAdbCommandToString] adb.exe: no devices/emulators found

`

**Comment by ApoQCL** [comment]
Same issue here.

**Comment by gillopillo** [comment]
yeah same here.

**Comment by renanstn** [comment]
Same issue here.

**Comment by whoindahouse** [comment]
Same

**Comment by Fenopy** [comment]
Please see our Telegram and/or Discord servers for current Server Status.
Due to a Provider issue, the Public Mirror is currently down.
This is NOT an application issue.

**Comment by zouille83** [comment]
Same for me
Have you a link to discord and telegram, I don't find you

**Comment by stormy1972** [comment]
hi all is it still down still getting nothing thank you

**Comment by FrancisFR** [comment]
Salut à tous, 
Je rencontre le meme problème pour se connecter au serveur.
J'ai exactement la même config que [hectorchanht]

**Comment by SCOTTxRT** [comment]
waiting for success

**Comment by Chax1** [comment]
We have brought the public mirror back online, you may encounter some messages like "Error 2" for 12-24 hours as the mirror has to catch up.

If you do receive it, please retry or wait a few hours and try again.
Thanks! 

Note: Please refrain from making issue posts like this on this repository, these are not application issues.
