### ISSUE TITLE
Option to skip any questions

### ISSUE THREAD

**Issue by DocMAX** [VRPirates/rookie#45]
Can we have an option to skip questions like "overwrite game?" if it's allready in the download dir. In general any question that stops the download of my queue.

**Comment by Fenopy** [comment]
No. This will not be added.

The Warning is there because the files already exist. If you want to sideload w/out downloading, drag and drop.

**Comment by DocMAX** [comment]
But it's impossible to run unattendet a list of multiple games... anyway. nevermind.
