### ISSUE TITLE
Child 'Edge WebView2' Spawned Windows Causing Rookie Startup Crash

### ISSUE THREAD

**Issue by prandleman** [VRPirates/rookie#46]
If you click links such as "this app is free click here to go to the github" it opens them with the systems default browser in a new window. On the other hand, links that are clicked within rookies preview frame (when display trailers instead of thumbnails is enabled) spawn up Microsoft Edge WebView2 windows. If these windows are left open and you restart Rookie, it will fail to load properly due to a file access denied error.

I'd provide the error message but this is easy enough to recreate the error. 

Possibly destroy all child spawned windows on rookie exit?

**Comment by Chax1** [comment]
I was able to reproduce this issue and have fixed it: #47
