### ISSUE TITLE
Feature Request: Ability to sort by total game downloads

### ISSUE THREAD

**Issue by flleeppyy** [VRPirates/rookie#53]
Just to see whats popular. Maybe ability to sort by "This Month", "This Year", "All Time"

**Comment by Fenopy** [comment]
This requires additional api work and is not currently planned.
However we are open source, so if anyone would like to contribute, feel free.

**Comment by rzfzr** [comment]
Does rsync provide this as metadata?

**Comment by Fenopy** [comment]
No, you it would require an api to hit each time a download is initiated or finished to log the information.

**Comment by Fenopy** [comment]
implemented in 2.30
