### ISSUE TITLE
Bug: Clicking on queue item removes it from the queue

### ISSUE THREAD

**Issue by flleeppyy** [VRPirates/rookie#54]
I hope this isn't intentional, I would assume right clicking then clicking a submenu item would suffice for deleting.

https://github.com/VRPirates/rookie/assets/18307183/b6388c48-3d09-4e2d-88d9-c55edecfd467

**Comment by Fenopy** [comment]
Working as designed.

**Comment by flleeppyy** [comment]
Okay, but IMO it shouldn't just delete from the queue when you click on it. Very annoying behavior and I'd much rather have an icon on the left side of the item to delete it from the queue
