### ISSUE TITLE
Feature Request/Bug fix?: Bring open prompts to the front when the main window becomes active

### ISSUE THREAD

**Issue by flleeppyy** [VRPirates/rookie#55]
I've occasionally opened Rookie to see that its "frozen", but it actually isn't, and there's a prompt open in the background that I have to alt-tab to.

Any time the main window is reopened, any open prompts/message boxes should be brought to the front.

**Comment by flleeppyy** [comment]
I would try to implement this myself but I'm not at a computer I can develop on.

**Comment by Fenopy** [comment]
Resolved in a pending PR for the next release.
