### ISSUE TITLE
Suggestion: calculate address based on hash of game content rather than game name

### ISSUE THREAD

**Issue by swiftsword94** [VRPirates/rookie#57]
Feel free to close this if its too big of a suggestion, however it would be better to address games based off of the hash of the content rather than the hash of the name as different versions can potentially conflict and rookie wouldn't be able to reconciliate between different versions of the game without changing the name (ie. beat saber's versions). So if any of the games have the same name you can have a hash collision (maybe CoD MWII?).

**Comment by Chax1** [comment]
This isn't an issue and never has been.

**Comment by Fenopy** [comment]
That is why games/releases have different names?
This is a suggestion that takes a simple straight forward solution and tries to complicate it for the sake of complicating it.

**Comment by swiftsword94** [comment]
Well this was mostly so that you would always have some address to store the game even if some games had the same name, but if you're not having that issue then that's fine. I guess it may not be worth the effort to implement it if only a few games share names.

**Comment by Fenopy** [comment]
No games share names.
