### ISSUE TITLE
7z Performance Enhancement

### ISSUE THREAD

**Issue by bluegamer3683Git** [VRPirates/rookie#63]
Hi, I discovered a way to hugely improve the performance of rookies during the extraction step.

For some reason the 7z.dll & 7z.exe that rookies uses only performs extraction on a single CPU core.

I have 7-Zip v23.1 x64 installed on my machine and if I take my copy of these two files and replace them on rookies, then rookies performs extraction using all CPU cores.

I would say most PCs these days have probably 4-8 cores, so that means this could easily result in a ~ 4-8x speed improvement!

With that said, I'm not sure of the exact difference between the 7zip version that you are using versus mine, but please consider updating 7z to one that supports multicore extraction 😊

**Comment by Chax1** [comment]
There was a particular reason as to why the 7z.dll & 7z.exe are older versions because the older ones still allow Rookie to run on 32 Bit hardware, however I could most likely implement a check for architecture and download the versions accordingly.

**Comment by Chax1** [comment]
This check is now implemented via #65
