### ISSUE TITLE
It keeps on saying that its unable to connect to the remote server. also I think the vrpirates wiki is down

### ISSUE THREAD

**Issue by Ap3xM4N** [VRPirates/rookie#69]

**Comment by Chax1** [comment]
This is not an application issue, but an internet issue. servers are up. use support channels (tg/discord), not git for support.
You can find a link to our Discord on our wiki page 🙂

**Comment by ilorenzom** [comment]
I second that, it is in fact an application issue. old versions connect, new v2.26 installs do not

**Comment by Fenopy** [comment]
This is not an application issue, but an internet issue. servers are up. use support channels (tg/discord), not git for support.
You can find a link to our Discord on our wiki page
