### ISSUE TITLE
vrp-public.json is only updated when the file already exists

### ISSUE THREAD

**Issue by DanTheMan827** [VRPirates/rookie#73]
Probably also the cause of #69 and similar issues.

Manually downloading https://vrpirates.wiki/downloads/vrp-public.json to the program directory fixed the issue shown.

![image](https://github.com/VRPirates/rookie/assets/790119/04210ead-5def-4108-a6d3-1eea1b76dc3c)

If you look at line 212 of MainForm.cs, there's a check enclosing the portion of the code responsible.

https://github.com/VRPirates/rookie/blob/0bf9a00af2c0f88745afb349c4c0200a400bb1fd/MainForm.cs#L212

I don't think this should be there?

The same is also true for the PCVR version and `vrp-public-pcvr.json`

**Comment by Chax1** [comment]
Works as intended, you wouldn't have the problem if youre downloading from our wiki as we package our releases with those files.

You're not supposed to DL off our GitHub really, the binaries here are meant for reference and for updating in-app updates.

**Comment by Fenopy** [comment]
As @Chax1 said, this is not an application issue. Rookie is designed to work with many configurations and automatically overriding/downloading a configuration file is not how it is intended to act.
