### ISSUE TITLE
When I Lauch Rookie SideLoaderit says this :(Unable to connect to Remote Server. Rookie is unable to connect to our Servers.  First time launching Rookie? Please relaunch and try again.  Things you can try: 1) Move the Rookie directory (Folder containing AndroidSideloader.exe) into C:\RSL 2) Try changing your systems DNS to either Cloudflare/Google/OpenDNS 3) Try using a systemwide VPN like ProtonVPN (which is free) 4) Sponsor a private server (https://vrpirates.wiki/en/Howto/sponsored-mirrors))

### ISSUE THREAD

**Issue by BahabaBeast** [VRPirates/rookie#86]
_**i Have Followed These instructions none of them works please help me with this

Unable to connect to Remote Server. Rookie is unable to connect to our Servers.

First time launching Rookie? Please relaunch and try again.

Things you can try:
1) Move the Rookie directory (Folder containing AndroidSideloader.exe) into C:\RSL
2) Try changing your systems DNS to either Cloudflare/Google/OpenDNS
3) Try using a systemwide VPN like ProtonVPN (which is free)
4) Sponsor a private server (https://vrpirates.wiki/en/Howto/sponsored-mirrors)**_

**Comment by Fenopy** [comment]
This is a connection issue on your end, and not an application problem.
Please use our Support Channels (Telegram or Discord) for support, not Git.

http://t.me/VRPirates


http://discord.gg/DcfEpwVa4a
