### ISSUE TITLE
obb file not found?

### ISSUE THREAD

**Issue by gamer6420** [VRPirates/rookie#92]
i try to install something but the app says The obb folder on the quest seems to not exist or be empty please redownload the game or sideload the obb folder manually. can someone help?
![Bild_2024-03-25_140240768](https://github.com/VRPirates/rookie/assets/148585213/feb09a2b-40a4-4dd0-978c-fc67dbaa168c)

**Comment by gamer6420** [comment]
![Bild_2024-03-25_142941963](https://github.com/VRPirates/rookie/assets/148585213/d9d96e58-e72c-4e6a-8be1-7f34ebb179c0)

**Comment by Chax1** [comment]
This is not an issue with our application, your device is not connected properly.

Use our support channels on Telegram or Discord for further help, not git.

http://t.me/VRPirates
http://discord.gg/DcfEpwVa4a
