### ISSUE TITLE
Rookie Sideloader 2.28 gets detected as Trojan:Win32/AgentTesla!ml

### ISSUE THREAD

**Issue by rickard-san** [VRPirates/rookie#97]
The latest release (2.28) is getting detected by Windows Defender ATP as Trojan:Win32/AgentTesla!ml

Can anyone confirm if this is a false positive detection or actually true?

**Comment by Chax1** [comment]
See #40

**Comment by rickard-san** [comment]
Hi @Chax1 
That is for version 2.25, and also as a different malware type.
Virus total doesn't have the latest version verified. The readme doesn't link to it at least.

**Comment by rickard-san** [comment]
Here is more information.
Malware Type/Classification: Trojan:Win32/AgentTesla!ml

Classification/name: Trojan:Win32/AgentTesla!ml
File Name: AndroidSideloader v2.28.exe
File Path: xxxxxxxxx\AndroidSideloader v2.28.exe
File Hash (SHA256): 989ebdeb5fc4114b6db0fc7f29e44e63ad42ece9842ca99a872fba33033f99bb

Description of malware: 
VirusTotal/AbuseIPDB Score: 3/72

Execution Timestamp: 10:44:24 AM
Event timeline:
Apr 5, 2024 10:44:54.384 AM - A cmd.exe script interpreter process was created by AndroidSideloader v2.28.exe
Apr 5, 2024 10:44:54.366 AM - AndroidSideloader v2.28.exe performed system information discovery
Apr 5, 2024 10:44:54.357 AM - AndroidSideloader v2.28.exe performed discovery indicative of virtualization/sandbox evasion
Apr 5, 2024 10:44:54.357 AM-  AndroidSideloader v2.28.exe executed the WMI query 'SELECT * FROM Win32_BIOS'
Apr 5, 2024 10:44:53.273 AM - AndroidSideloader v2.28.exe performed system hardware discovery
Apr 5, 2024 10:44:53.273 AM - AndroidSideloader v2.28.exe executed the WMI query 'SELECT * FROM Win32_Processor'

**Comment by Fenopy** [comment]
The !ml at the end of the virus type indicates "Machine Learning", meaning the Anti-Virus is just guessing it may be a virus due to some code patterns.
Below is the snippet we send to users in our support chats and it still is valid for all versions-

No, none of the Applications here are a virus. It’s a false positive due to the apps being Unsigned by a Corporation.
Make sure you’re downloading from our wiki!
As always, the source code is available to review and compile on our Git.
[Information about False Positives](https://www.howtogeek.com/180162/how-to-tell-if-a-virus-is-actually-a-false-positive/)

**Comment by rickard-san** [comment]
> The !ml at the end of the virus type indicates "Machine Learning", meaning the Anti-Virus is just guessing it may be a virus due to some code patterns.
> Below is the snippet we send to users in our support chats and it still is valid for all versions-
> 
> No, none of the Applications here are a virus. It’s a false positive due to the apps being Unsigned by a Corporation.
> Make sure you’re downloading from our wiki!
> As always, the source code is available to review and compile on our Git.
> [Information about False Positives](https://www.howtogeek.com/180162/how-to-tell-if-a-virus-is-actually-a-false-positive/)

Thank you for clarification.

**Comment by unknownslayer64th-arch** [comment]
https://www.virustotal.com/gui/file/a329b31b2fda9f72c907b2688f6ee6d64b2e1a9a0d8efd186b3d64b930550800/detection
